_MACOSX_DEPLOYMENT_TARGET_:
  - "10.9"
  - "10.10"
  - "10.11"
  - "10.12"
  - "10.13"
  - "10.13"
  - "10.14"
  - "10.15"
  - "11.0"
  - "11.1"
  - "11.3"
  - "12.0"
  - "12.1"
  - "12.3"
  - "13.0"
  - "13.1"
  - "13.3"

cross_target_platform:
  - osx-64
  - osx-arm64
