_MACOSX_DEPLOYMENT_TARGET_:
- '14.5'
cdt_name:
- conda
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cross_target_platform:
- osx-arm64
docker_image:
- quay.io/condaforge/linux-anvil-x86_64:alma9
target_platform:
- linux-64
